export const SYSTEM_PERMISSIONS = {
    // --- AGENT PAGES ---
    PAGE_AGENT_DASHBOARD: 'page_agent_dashboard',
    PAGE_AGENT_GROUPS: 'page_agent_groups',
    PAGE_AGENT_MEMBERS: 'page_agent_members',
    PAGE_AGENT_REPORTS: 'page_agent_reports',
    PAGE_AGENT_ROLES: 'page_agent_roles',
    PAGE_AGENT_SETTINGS: 'page_agent_settings',
    PAGE_AGENT_SUPPORT: 'page_agent_support',
    PAGE_AGENT_TRAINING: 'page_agent_training',
    PAGE_AGENT_AUDIT: 'page_agent_audit',
    PAGE_AGENT_COMMUNICATIONS: 'page_agent_communications',
    PAGE_AGENT_COMPLIANCE: 'page_agent_compliance',

    // --- CASHIER PAGES ---
    PAGE_CASHIER_DASHBOARD: 'page_cashier_dashboard',
    PAGE_CASHIER_CONTRIBUTIONS: 'page_cashier_contributions',
    PAGE_CASHIER_LOANS: 'page_cashier_loans',
    PAGE_CASHIER_FINES: 'page_cashier_fines',
    PAGE_CASHIER_REPORTS: 'page_cashier_reports',
    PAGE_CASHIER_SETTINGS: 'page_cashier_settings',
    PAGE_CASHIER_SUPPORT: 'page_cashier_support',
    PAGE_CASHIER_AUDIT: 'page_cashier_audit',
    PAGE_CASHIER_NOTIFICATIONS: 'page_cashier_notifications',
    PAGE_CASHIER_OVERVIEW: 'page_cashier_overview',
    PAGE_CASHIER_RECORDS: 'page_cashier_records',
    PAGE_CASHIER_SCHEDULE: 'page_cashier_schedule',

    // --- GROUP ADMIN PAGES ---
    PAGE_GROUP_ADMIN_DASHBOARD: 'page_group_admin_dashboard',
    PAGE_GROUP_ADMIN_MEMBERS: 'page_group_admin_members',
    PAGE_GROUP_ADMIN_CONTRIBUTIONS: 'page_group_admin_contributions',
    PAGE_GROUP_ADMIN_LOAN_REQUESTS: 'page_group_admin_loan_requests',
    PAGE_GROUP_ADMIN_FINES: 'page_group_admin_fines',
    PAGE_GROUP_ADMIN_MEETINGS: 'page_group_admin_meetings',
    PAGE_GROUP_ADMIN_SETTINGS: 'page_group_admin_settings',
    PAGE_GROUP_ADMIN_ANALYTICS: 'page_group_admin_analytics',
    PAGE_GROUP_ADMIN_ANNOUNCEMENTS: 'page_group_admin_announcements',
    PAGE_GROUP_ADMIN_LEARN_GROW: 'page_group_admin_learn_grow',
    PAGE_GROUP_ADMIN_MEMBER_APPLICATIONS: 'page_group_admin_member_applications',
    PAGE_GROUP_ADMIN_SUPPORT: 'page_group_admin_support',
    PAGE_GROUP_ADMIN_TRANSACTIONS: 'page_group_admin_transactions',
    PAGE_GROUP_ADMIN_VOTING: 'page_group_admin_voting',
    PAGE_GROUP_ADMIN_AGENT: 'page_group_admin_agent',

    // --- MEMBER PAGES ---
    PAGE_MEMBER_DASHBOARD: 'page_member_dashboard',
    PAGE_MEMBER_SAVINGS: 'page_member_savings',
    PAGE_MEMBER_LOANS: 'page_member_loans',
    PAGE_MEMBER_FINES: 'page_member_fines',
    PAGE_MEMBER_MEETINGS: 'page_member_meetings',
    PAGE_MEMBER_SETTINGS: 'page_member_settings',
    PAGE_MEMBER_ANNOUNCEMENTS: 'page_member_announcements',
    PAGE_MEMBER_GROUP: 'page_member_group',
    PAGE_MEMBER_LEARN_GROW: 'page_member_learn_grow',
    PAGE_MEMBER_SUPPORT: 'page_member_support',
    PAGE_MEMBER_TRANSACTIONS: 'page_member_transactions',
    PAGE_MEMBER_VOTING: 'page_member_voting',

    // --- SECRETARY PAGES ---
    PAGE_SECRETARY_DASHBOARD: 'page_secretary_dashboard',
    PAGE_SECRETARY_MEMBERS: 'page_secretary_members',
    PAGE_SECRETARY_MEETINGS: 'page_secretary_meetings',
    PAGE_SECRETARY_REPORTS: 'page_secretary_reports',
    PAGE_SECRETARY_SETTINGS: 'page_secretary_settings',
    PAGE_SECRETARY_ARCHIVE: 'page_secretary_archive',
    PAGE_SECRETARY_COMMUNICATIONS: 'page_secretary_communications',
    PAGE_SECRETARY_COMPLIANCE: 'page_secretary_compliance',
    PAGE_SECRETARY_DOCUMENTATION: 'page_secretary_documentation',
    PAGE_SECRETARY_NOTIFICATIONS: 'page_secretary_notifications',
    PAGE_SECRETARY_SUPPORT: 'page_secretary_support',
    PAGE_SECRETARY_TRAINING: 'page_secretary_training',
    PAGE_SECRETARY_TRANSACTIONS: 'page_secretary_transactions',

    // --- SYSTEM ADMIN PAGES ---
    PAGE_SYSTEM_ADMIN_DASHBOARD: 'page_system_admin_dashboard',
    PAGE_SYSTEM_ADMIN_USERS: 'page_system_admin_users',
    PAGE_SYSTEM_ADMIN_BRANCHES: 'page_system_admin_branches',
    PAGE_SYSTEM_ADMIN_REPORTS: 'page_system_admin_reports',
    PAGE_SYSTEM_ADMIN_SETTINGS: 'page_system_admin_settings', // Mapped to SystemAdminSystem.jsx
    PAGE_SYSTEM_ADMIN_AGENTS: 'page_system_admin_agents',
    PAGE_SYSTEM_ADMIN_AUDIT: 'page_system_admin_audit',
    PAGE_SYSTEM_ADMIN_CLIENTS: 'page_system_admin_clients',
    PAGE_SYSTEM_ADMIN_COMMUNICATIONS: 'page_system_admin_communications',
    PAGE_SYSTEM_ADMIN_LEARN_GROW: 'page_system_admin_learn_grow',
    PAGE_SYSTEM_ADMIN_LOANS: 'page_system_admin_loans',
    PAGE_SYSTEM_ADMIN_SUPPORT: 'page_system_admin_support',
    PAGE_SYSTEM_ADMIN_TRANSACTIONS: 'page_system_admin_transactions',

    // --- API / FEATURES ---
    ACTION_MANAGE_USERS: 'action_manage_users',
    ACTION_MANAGE_GROUPS: 'action_manage_groups',
    ACTION_MANAGE_LOANS: 'action_manage_loans',
    ACTION_MANAGE_CONTRIBUTIONS: 'action_manage_contributions',
    ACTION_MANAGE_FINES: 'action_manage_fines',
    ACTION_VIEW_REPORTS: 'action_view_reports',
    ACTION_VIEW_ANALYTICS: 'action_view_analytics',
    ACTION_SEND_NOTIFICATIONS: 'action_send_notifications',
    ACTION_VIEW_AUDIT_LOGS: 'action_view_audit_logs',
    ACTION_MANAGE_SYSTEM_SETTINGS: 'action_manage_system_settings',
    ACTION_MANAGE_SUPPORT: 'action_manage_support'
};

export const PERMISSION_GROUPS = {
    AGENT: [
        SYSTEM_PERMISSIONS.PAGE_AGENT_DASHBOARD, SYSTEM_PERMISSIONS.PAGE_AGENT_GROUPS, SYSTEM_PERMISSIONS.PAGE_AGENT_MEMBERS,
        SYSTEM_PERMISSIONS.PAGE_AGENT_REPORTS, SYSTEM_PERMISSIONS.PAGE_AGENT_ROLES, SYSTEM_PERMISSIONS.PAGE_AGENT_SETTINGS,
        SYSTEM_PERMISSIONS.PAGE_AGENT_SUPPORT, SYSTEM_PERMISSIONS.PAGE_AGENT_TRAINING, SYSTEM_PERMISSIONS.PAGE_AGENT_AUDIT,
        SYSTEM_PERMISSIONS.PAGE_AGENT_COMMUNICATIONS, SYSTEM_PERMISSIONS.PAGE_AGENT_COMPLIANCE
    ],
    CASHIER: [
        SYSTEM_PERMISSIONS.PAGE_CASHIER_DASHBOARD, SYSTEM_PERMISSIONS.PAGE_CASHIER_CONTRIBUTIONS, SYSTEM_PERMISSIONS.PAGE_CASHIER_LOANS,
        SYSTEM_PERMISSIONS.PAGE_CASHIER_FINES, SYSTEM_PERMISSIONS.PAGE_CASHIER_REPORTS, SYSTEM_PERMISSIONS.PAGE_CASHIER_SETTINGS,
        SYSTEM_PERMISSIONS.PAGE_CASHIER_SUPPORT, SYSTEM_PERMISSIONS.PAGE_CASHIER_AUDIT, SYSTEM_PERMISSIONS.PAGE_CASHIER_NOTIFICATIONS,
        SYSTEM_PERMISSIONS.PAGE_CASHIER_OVERVIEW, SYSTEM_PERMISSIONS.PAGE_CASHIER_RECORDS, SYSTEM_PERMISSIONS.PAGE_CASHIER_SCHEDULE
    ],
    GROUP_ADMIN: [
        SYSTEM_PERMISSIONS.PAGE_GROUP_ADMIN_DASHBOARD, SYSTEM_PERMISSIONS.PAGE_GROUP_ADMIN_MEMBERS, SYSTEM_PERMISSIONS.PAGE_GROUP_ADMIN_CONTRIBUTIONS,
        SYSTEM_PERMISSIONS.PAGE_GROUP_ADMIN_LOAN_REQUESTS, SYSTEM_PERMISSIONS.PAGE_GROUP_ADMIN_FINES, SYSTEM_PERMISSIONS.PAGE_GROUP_ADMIN_MEETINGS,
        SYSTEM_PERMISSIONS.PAGE_GROUP_ADMIN_SETTINGS, SYSTEM_PERMISSIONS.PAGE_GROUP_ADMIN_ANALYTICS, SYSTEM_PERMISSIONS.PAGE_GROUP_ADMIN_ANNOUNCEMENTS,
        SYSTEM_PERMISSIONS.PAGE_GROUP_ADMIN_LEARN_GROW, SYSTEM_PERMISSIONS.PAGE_GROUP_ADMIN_MEMBER_APPLICATIONS, SYSTEM_PERMISSIONS.PAGE_GROUP_ADMIN_SUPPORT,
        SYSTEM_PERMISSIONS.PAGE_GROUP_ADMIN_TRANSACTIONS, SYSTEM_PERMISSIONS.PAGE_GROUP_ADMIN_VOTING, SYSTEM_PERMISSIONS.PAGE_GROUP_ADMIN_AGENT
    ],
    MEMBER: [
        SYSTEM_PERMISSIONS.PAGE_MEMBER_DASHBOARD, SYSTEM_PERMISSIONS.PAGE_MEMBER_SAVINGS, SYSTEM_PERMISSIONS.PAGE_MEMBER_LOANS,
        SYSTEM_PERMISSIONS.PAGE_MEMBER_FINES, SYSTEM_PERMISSIONS.PAGE_MEMBER_MEETINGS, SYSTEM_PERMISSIONS.PAGE_MEMBER_SETTINGS,
        SYSTEM_PERMISSIONS.PAGE_MEMBER_ANNOUNCEMENTS, SYSTEM_PERMISSIONS.PAGE_MEMBER_GROUP, SYSTEM_PERMISSIONS.PAGE_MEMBER_LEARN_GROW,
        SYSTEM_PERMISSIONS.PAGE_MEMBER_SUPPORT, SYSTEM_PERMISSIONS.PAGE_MEMBER_TRANSACTIONS, SYSTEM_PERMISSIONS.PAGE_MEMBER_VOTING
    ],
    SECRETARY: [
        SYSTEM_PERMISSIONS.PAGE_SECRETARY_DASHBOARD, SYSTEM_PERMISSIONS.PAGE_SECRETARY_MEMBERS, SYSTEM_PERMISSIONS.PAGE_SECRETARY_MEETINGS,
        SYSTEM_PERMISSIONS.PAGE_SECRETARY_REPORTS, SYSTEM_PERMISSIONS.PAGE_SECRETARY_SETTINGS, SYSTEM_PERMISSIONS.PAGE_SECRETARY_ARCHIVE,
        SYSTEM_PERMISSIONS.PAGE_SECRETARY_COMMUNICATIONS, SYSTEM_PERMISSIONS.PAGE_SECRETARY_COMPLIANCE, SYSTEM_PERMISSIONS.PAGE_SECRETARY_DOCUMENTATION,
        SYSTEM_PERMISSIONS.PAGE_SECRETARY_NOTIFICATIONS, SYSTEM_PERMISSIONS.PAGE_SECRETARY_SUPPORT, SYSTEM_PERMISSIONS.PAGE_SECRETARY_TRAINING,
        SYSTEM_PERMISSIONS.PAGE_SECRETARY_TRANSACTIONS
    ],
    SYSTEM_ADMIN: [
        SYSTEM_PERMISSIONS.PAGE_SYSTEM_ADMIN_DASHBOARD, SYSTEM_PERMISSIONS.PAGE_SYSTEM_ADMIN_USERS, SYSTEM_PERMISSIONS.PAGE_SYSTEM_ADMIN_BRANCHES,
        SYSTEM_PERMISSIONS.PAGE_SYSTEM_ADMIN_REPORTS, SYSTEM_PERMISSIONS.PAGE_SYSTEM_ADMIN_SETTINGS, SYSTEM_PERMISSIONS.PAGE_SYSTEM_ADMIN_AGENTS,
        SYSTEM_PERMISSIONS.PAGE_SYSTEM_ADMIN_AUDIT, SYSTEM_PERMISSIONS.PAGE_SYSTEM_ADMIN_CLIENTS, SYSTEM_PERMISSIONS.PAGE_SYSTEM_ADMIN_COMMUNICATIONS,
        SYSTEM_PERMISSIONS.PAGE_SYSTEM_ADMIN_LEARN_GROW, SYSTEM_PERMISSIONS.PAGE_SYSTEM_ADMIN_LOANS, SYSTEM_PERMISSIONS.PAGE_SYSTEM_ADMIN_SUPPORT,
        SYSTEM_PERMISSIONS.PAGE_SYSTEM_ADMIN_TRANSACTIONS
    ],
    ACTIONS: [
        SYSTEM_PERMISSIONS.ACTION_MANAGE_USERS, SYSTEM_PERMISSIONS.ACTION_MANAGE_GROUPS, SYSTEM_PERMISSIONS.ACTION_MANAGE_LOANS,
        SYSTEM_PERMISSIONS.ACTION_MANAGE_CONTRIBUTIONS, SYSTEM_PERMISSIONS.ACTION_MANAGE_FINES, SYSTEM_PERMISSIONS.ACTION_VIEW_REPORTS,
        SYSTEM_PERMISSIONS.ACTION_VIEW_ANALYTICS, SYSTEM_PERMISSIONS.ACTION_SEND_NOTIFICATIONS, SYSTEM_PERMISSIONS.ACTION_VIEW_AUDIT_LOGS,
        SYSTEM_PERMISSIONS.ACTION_MANAGE_SYSTEM_SETTINGS, SYSTEM_PERMISSIONS.ACTION_MANAGE_SUPPORT
    ]
};

export const ROLE_DEFAULT_PERMISSIONS = {
    'Agent': PERMISSION_GROUPS.AGENT,
    'Cashier': PERMISSION_GROUPS.CASHIER,
    'Group Admin': PERMISSION_GROUPS.GROUP_ADMIN,
    'Member': PERMISSION_GROUPS.MEMBER,
    'Secretary': PERMISSION_GROUPS.SECRETARY,
    'System Admin': [
        ...PERMISSION_GROUPS.SYSTEM_ADMIN,
        ...PERMISSION_GROUPS.ACTIONS
    ]
};
